[package]
name = "om-rust-bm"
version = "0.1.0"
edition = "2024"

[dependencies]
omfiles = { git = "https://github.com/open-meteo/rust-omfiles", rev = "fffe1f151a26ad5ab688615269260811767f32ac" }
clap = "2.33"
